from pathlib import Path


def replace_once(path: str, old: str, new: str):
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one match, found {count}: {old[:80]!r}")
    p.write_text(text.replace(old, new, 1))


# Workspace membership and dependencies.
replace_once(
    "Cargo.toml",
    '    "crates/scirust-verify-scirust",\n    "crates/scirust-verify-cli",',
    '    "crates/scirust-verify-scirust",\n    "crates/scirust-verify-signature",\n    "crates/scirust-verify-cli",',
)
replace_once(
    "Cargo.toml",
    'scirust-verify-scirust = { path = "crates/scirust-verify-scirust" }\n\nserde =',
    'scirust-verify-scirust = { path = "crates/scirust-verify-scirust" }\nscirust-verify-signature = { path = "crates/scirust-verify-signature" }\n\nserde =',
)
replace_once(
    "Cargo.toml",
    'clap = { version = "4", features = ["derive"] }\n',
    'clap = { version = "4", features = ["derive"] }\ned25519-dalek = { version = "2", features = ["rand_core"] }\nrand_core = { version = "0.6", features = ["getrandom"] }\n',
)
replace_once(
    "crates/scirust-verify-cli/Cargo.toml",
    'scirust-verify-scirust = { workspace = true }\nscirust-verify-report = { workspace = true }',
    'scirust-verify-scirust = { workspace = true }\nscirust-verify-signature = { workspace = true }\nscirust-verify-report = { workspace = true }',
)

# CLI wiring.
replace_once(
    "crates/scirust-verify-cli/src/main.rs",
    'mod scirust_ingest;\n',
    'mod scirust_ingest;\nmod signature_cli;\n',
)
replace_once(
    "crates/scirust-verify-cli/src/main.rs",
    '    /// Ingest a completed SciRust test-protocol evidence bundle into a new dossier run.\n    IngestScirust {',
    '''    /// Generate a fresh Ed25519 dossier-signing keypair.\n    Keygen {\n        /// Private-key JSON path. Never printed; mode 0600 on Unix.\n        #[arg(long)]\n        private_key: PathBuf,\n        /// Public-key JSON path.\n        #[arg(long)]\n        public_key: PathBuf,\n        /// Overwrite existing regular files (symbolic links remain rejected).\n        #[arg(long)]\n        force: bool,\n    },\n    /// Sign a finalized, integrity-valid evidence dossier with Ed25519.\n    Sign {\n        /// Run id to sign.\n        run: String,\n        /// Private signing key generated by `keygen`.\n        #[arg(long)]\n        private_key: PathBuf,\n        /// Project root containing `.scirust-verify`.\n        #[arg(long)]\n        project: Option<PathBuf>,\n        /// Replace an existing detached signature for this run/key.\n        #[arg(long)]\n        force: bool,\n    },\n    /// Verify a detached dossier signature against an explicit public key.\n    VerifySignature {\n        /// Run id whose finalized bundle is being authenticated.\n        run: String,\n        /// Public key whose provenance the caller has chosen to trust.\n        #[arg(long)]\n        public_key: PathBuf,\n        /// Explicit detached signature path; defaults to the key-id-derived path.\n        #[arg(long)]\n        signature: Option<PathBuf>,\n        /// Project root containing `.scirust-verify`.\n        #[arg(long)]\n        project: Option<PathBuf>,\n    },\n    /// Ingest a completed SciRust test-protocol evidence bundle into a new dossier run.\n    IngestScirust {''',
)
replace_once(
    "crates/scirust-verify-cli/src/main.rs",
    '        Command::Doctor => doctor(),\n        Command::Schema => schema(),\n        Command::IngestScirust {',
    '''        Command::Doctor => doctor(),\n        Command::Schema => schema(),\n        Command::Keygen {\n            private_key,\n            public_key,\n            force,\n        } => signature_cli::keygen(private_key, public_key, force, cli.json),\n        Command::Sign {\n            run,\n            private_key,\n            project,\n            force,\n        } => signature_cli::sign(&run, private_key, project, force, cli.json),\n        Command::VerifySignature {\n            run,\n            public_key,\n            signature,\n            project,\n        } => signature_cli::verify_signature(&run, public_key, signature, project, cli.json),\n        Command::IngestScirust {''',
)
replace_once(
    "crates/scirust-verify-cli/src/main.rs",
    '        ("bundle.json", "Integrity manifest sealing every file"),\n        ("report.json / report.md", "Regenerable reports"),',
    '        ("bundle.json", "Integrity manifest sealing every file"),\n        ("signatures/<run>/<key-id>.json", "Detached Ed25519 signature metadata"),\n        ("report.json / report.md", "Regenerable reports"),',
)

# CLI E2E coverage.
e2e = Path("crates/scirust-verify-cli/tests/e2e.rs")
text = e2e.read_text()
marker = '''\nfn tempfile_dir(tag: &str) -> PathBuf {'''
if marker not in text:
    raise SystemExit("e2e tempfile_dir marker missing")
new_tests = r'''

#[test]
fn signed_dossier_roundtrip_and_wrong_key_rejection() {
    prebuild_fixtures();
    let project = fixture("passing-project");
    let store = tempfile_dir("signature-roundtrip");
    let output = store.join(".scirust-verify");
    let verify = cli()
        .args([
            "verify",
            project.to_str().unwrap(),
            "--output",
            output.to_str().unwrap(),
        ])
        .env("CARGO_TARGET_DIR", project.join("target"))
        .output()
        .unwrap();
    assert!(verify.status.success(), "{}", String::from_utf8_lossy(&verify.stderr));
    let run = latest_run_in(&output.join("runs"));

    let keys = store.join("keys");
    std::fs::create_dir_all(&keys).unwrap();
    let private_a = keys.join("a.json");
    let public_a = keys.join("a.pub.json");
    let private_b = keys.join("b.json");
    let public_b = keys.join("b.pub.json");
    let keygen = cli()
        .args([
            "keygen",
            "--private-key",
            private_a.to_str().unwrap(),
            "--public-key",
            public_a.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert!(keygen.status.success(), "{}", String::from_utf8_lossy(&keygen.stderr));
    let secret_doc = std::fs::read_to_string(&private_a).unwrap();
    let secret_hex = serde_json::from_str::<serde_json::Value>(&secret_doc).unwrap()
        ["secret_key_hex"]
        .as_str()
        .unwrap()
        .to_owned();
    assert!(!String::from_utf8_lossy(&keygen.stdout).contains(&secret_hex));

    let signed = cli()
        .args([
            "sign",
            &run,
            "--private-key",
            private_a.to_str().unwrap(),
            "--project",
            store.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert!(signed.status.success(), "{}", String::from_utf8_lossy(&signed.stderr));

    let checked = cli()
        .args([
            "--json",
            "verify-signature",
            &run,
            "--public-key",
            public_a.to_str().unwrap(),
            "--project",
            store.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert!(checked.status.success(), "{}", String::from_utf8_lossy(&checked.stderr));
    let doc: serde_json::Value = serde_json::from_slice(&checked.stdout).unwrap();
    assert_eq!(doc["cryptographically_valid"].as_bool(), Some(true));
    assert!(doc["trust_scope"].as_str().unwrap().contains("signer identity"));

    assert!(cli()
        .args([
            "keygen",
            "--private-key",
            private_b.to_str().unwrap(),
            "--public-key",
            public_b.to_str().unwrap(),
        ])
        .output()
        .unwrap()
        .status
        .success());
    let wrong = cli()
        .args([
            "verify-signature",
            &run,
            "--public-key",
            public_b.to_str().unwrap(),
            "--project",
            store.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert_eq!(wrong.status.code(), Some(1));
}

#[test]
fn corrupted_dossier_cannot_be_signed() {
    prebuild_fixtures();
    let project = fixture("passing-project");
    let store = tempfile_dir("signature-corrupt");
    let output = store.join(".scirust-verify");
    let verify = cli()
        .args([
            "verify",
            project.to_str().unwrap(),
            "--output",
            output.to_str().unwrap(),
        ])
        .env("CARGO_TARGET_DIR", project.join("target"))
        .output()
        .unwrap();
    assert!(verify.status.success());
    let run = latest_run_in(&output.join("runs"));
    std::fs::write(output.join("runs").join(&run).join("report.md"), "tampered\n").unwrap();

    let private = store.join("private.json");
    let public = store.join("public.json");
    assert!(cli()
        .args([
            "keygen",
            "--private-key",
            private.to_str().unwrap(),
            "--public-key",
            public.to_str().unwrap(),
        ])
        .output()
        .unwrap()
        .status
        .success());
    let sign = cli()
        .args([
            "sign",
            &run,
            "--private-key",
            private.to_str().unwrap(),
            "--project",
            store.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert_eq!(sign.status.code(), Some(1));
    assert!(!store.join(".scirust-verify/signatures").exists());
}
'''
text = text.replace(marker, new_tests + marker, 1)
e2e.write_text(text)

# README command flow and semantics.
replace_once(
    "README.md",
    '# 10. Persisted document catalog.\nscirust-verify schema\n```',
    '''# 10. Persisted document catalog.\nscirust-verify schema\n\n# 11. Generate an Ed25519 keypair, sign a finalized dossier, and verify it.\nscirust-verify keygen --private-key ~/.config/scirust-verify/key.json --public-key ~/.config/scirust-verify/key.pub.json\nscirust-verify sign <run-id> --private-key ~/.config/scirust-verify/key.json\nscirust-verify verify-signature <run-id> --public-key ~/.config/scirust-verify/key.pub.json\n```''',
)
replace_once(
    "README.md",
    '## Development\n',
    '''## Signed evidence dossiers\n\nFinalized dossiers can be authenticated with detached Ed25519 signatures. The\nsignature binds the exact `bundle.json` bytes and run id without mutating the\nsealed evidence directory. Signature files live under\n`.scirust-verify/signatures/<run-id>/`. A successful signature check proves\nvalidity under the **explicitly supplied public key**; it does not by itself\nprove signer identity, key authorization/revocation, or trusted timestamping.\nSee [SIGNATURES.md](docs/SIGNATURES.md).\n\n## Development\n''',
)

print("signed dossier integration patch applied")
